import type { ContentSnapshot } from './content-schema'

export const SEED_CONTENT: ContentSnapshot = {
  personal: {
    name: 'Ramjith Radhakrishnan',
    title: 'Automotive Software & Test Engineer',
    tagline: 'Building Safer Vehicles. Smarter Systems. Faster Futures.',
    bio: 'Senior Automotive Software & Test Engineer with 10+ years building safer vehicles and smarter systems. Currently Project Lead at Volvo Cars, leading validation for next-gen EV platforms.',
    location: 'Gothenburg, Sweden',
    email: 'iamramjith@outlook.com',
    linkedin: 'https://www.linkedin.com/in/ramjith-radhakrishnan-97ba05191/',
    github: '',
    currentCompany: 'Volvo Cars Corporation',
    image: '',
  },
  stats: [
    { id: 's1', value: 10, suffix: '+', label: 'Years Experience' },
    { id: 's2', value: 4, suffix: '', label: 'Global Companies' },
    { id: 's3', value: 14, suffix: '+', label: 'Engineers Led' },
    { id: 's4', value: 250, suffix: '+', label: 'Critical Defects Prevented' },
  ],
  career: [
    {
      id: 'c1',
      company: 'Tata Consultancy Services',
      short: 'TCS',
      role: 'Software Engineer',
      period: 'Sep 2016 – Nov 2018',
      location: 'Chennai, India',
      focus: 'Telematics & Infotainment',
      color: '#0066cc',
      achievements: [
        'Conducted system & functional testing of Telematics Control Units and Infotainment ECUs',
        'Validated Bluetooth profiles including HFP and A2DP for in-vehicle infotainment',
        'Improved release readiness through structured defect tracking and regression validation',
      ],
      tools: ['CANoe', 'CANalyzer', 'Jira', 'IBM DOORS', 'ECU Test'],
    },
    {
      id: 'c2',
      company: 'HCL Technologies',
      short: 'HCL',
      role: 'Senior Software Engineer',
      period: 'Nov 2018 – Nov 2021',
      location: 'Bangalore, India',
      focus: 'AUTOSAR & ADAS Testing',
      color: '#e31937',
      achievements: [
        'Developed MCAL drivers (MCU, Port, DIO) for rear-view camera systems',
        'Performed MISRA static analysis and compliance checks',
        'Executed interface-level validation for ADAS programs (Ford)',
        'Enhanced code quality and integration reliability across safety-critical systems',
      ],
      tools: ['AUTOSAR', 'Embedded C', 'VectorCAST', 'Helix QAC', 'IBM DOORS', 'ARM DS5'],
    },
    {
      id: 'c3',
      company: 'L&T Technology Services',
      short: 'LTTS',
      role: 'Senior Engineer',
      period: 'Nov 2021 – Dec 2022',
      location: 'Mysore, India',
      focus: 'Passenger Occupancy Detection Systems',
      color: '#f97316',
      achievements: [
        'Led system testing for new PODS platform',
        'Achieved 99% test case coverage',
        'Identified 25+ critical defects before vehicle integration',
        'Worked with Stellantis, Hyundai, Daimler, BMW, Audi programs',
      ],
      tools: ['Polarion', 'CANoe', 'CANalyzer', 'ETAS INCA', 'GIT'],
    },
    {
      id: 'c4',
      company: 'Volvo Cars',
      short: 'VOLVO',
      role: 'Project Lead – Exterior Systems',
      period: 'Feb 2023 – Present',
      location: 'Gothenburg, Sweden',
      focus: 'EV Programs – Exterior Systems Validation',
      color: '#003057',
      achievements: [
        'Lead validation for next-gen EV platforms: EX90, EX30, ES90, Polestar programs',
        'Reduced manual testing effort by 50% using CAPL + vTestStudio automation',
        'Managed team of 8 engineers across multiple ECU domains',
        'Improved issue resolution time by 25%',
        'Delivered 100% on-time milestones for critical launches',
      ],
      tools: ['CANoe', 'CANalyzer', 'CAPL', 'vTestStudio', 'Polarion', 'Ethernet', 'WireShark'],
    },
  ],
  timeline: [
    { id: 'lt1', year: '1994', title: 'Born in Pollachi', description: 'Grew up in Pollachi, Tamil Nadu — a small city that nurtured big ambitions and grounded values.', category: 'life', pinned: false },
    { id: 'lt2', year: '2012', title: 'Engineering Begins', description: 'Joined Anna University for B.E. Computer Science Engineering — the first committed step into technology.', category: 'education', pinned: false },
    { id: 'lt3', year: '2016', title: 'Career Launch at TCS', description: 'First professional role at Tata Consultancy Services, Chennai. Telematics & Infotainment ECU testing for major OEMs.', category: 'career', pinned: false },
    { id: 'lt4', year: '2018', title: 'HCL Technologies', description: 'Relocated to Bangalore. Deep specialisation in AUTOSAR, ADAS validation, and Embedded C for Ford safety-critical programs.', category: 'career', pinned: false },
    { id: 'lt-marry', year: '2021', title: 'Married Maneesha Raj Peringayil', description: '16 June 2021 — Married the love of my life, Maneesha Raj Peringayil. The most important chapter, written together.', category: 'milestone', pinned: true },
    { id: 'lt5', year: '2021', title: 'L&T Technology Services', description: 'Moved to Mysore. Led complete system testing for Passenger Occupancy Detection Systems. Achieved 99% test coverage.', category: 'career', pinned: false },
    { id: 'lt6', year: '2022', title: 'Became a Mentor', description: 'Began actively mentoring junior engineers in test automation, AUTOSAR fundamentals, and career navigation.', category: 'personal', pinned: false },
    { id: 'lt7', year: '2023', title: 'Volvo Cars — Gothenburg', description: 'International relocation to Sweden. Joined Volvo Cars as Project Lead for EV exterior systems. Programs: EX90, EX30, ES90, Polestar.', category: 'career', pinned: false },
    { id: 'lt8', year: '2024', title: 'Volvo Track Licence T1 & T2', description: 'Earned Volvo Cars track driving certification — T1 and T2 licences earned on the official Volvo test track in Gothenburg.', category: 'milestone', pinned: false },
    { id: 'lt9', year: '2025', title: 'Building Forward', description: 'Continuing EV validation leadership at Volvo. Expanding expertise in AI-augmented automotive testing and next-gen mobility.', category: 'current', pinned: true },
  ],
  projects: [
    {
      id: 'p1',
      title: 'EV Exterior Validation Suite',
      description: 'Automated validation framework for Volvo EX90/EX30 exterior ECUs. Reduced manual test effort by 50%.',
      tech: ['CAPL', 'vTestStudio', 'CANoe', 'Python'],
      image: '',
      url: '',
      repo: '',
      featured: true,
    },
    {
      id: 'p2',
      title: 'PODS Test Platform',
      description: 'Passenger Occupancy Detection System test platform achieving 99% test coverage.',
      tech: ['Python', 'Polarion', 'CANoe', 'pytest'],
      image: '',
      url: '',
      repo: '',
      featured: true,
    },
  ],
  skillCategories: [
    {
      id: 'sc1',
      name: 'Automotive',
      description: 'ECU, ADAS, EV Systems, CAN/LIN protocols',
      color: '#00ff87',
      skills: [
        { id: 'sk1', name: 'AUTOSAR', proficiency: 5 },
        { id: 'sk2', name: 'CAN', proficiency: 5 },
        { id: 'sk3', name: 'LIN', proficiency: 5 },
        { id: 'sk4', name: 'UDS', proficiency: 4 },
        { id: 'sk5', name: 'Ethernet', proficiency: 4 },
        { id: 'sk6', name: 'ADAS', proficiency: 5 },
        { id: 'sk7', name: 'EV Systems', proficiency: 4 },
        { id: 'sk8', name: 'ECU Testing', proficiency: 5 },
      ],
    },
    {
      id: 'sc2',
      name: 'Safety',
      description: 'Functional safety & compliance standards',
      color: '#c9a84c',
      skills: [
        { id: 'sk9', name: 'ISO 26262', proficiency: 5 },
        { id: 'sk10', name: 'ISO 21434', proficiency: 4 },
        { id: 'sk11', name: 'ASPICE', proficiency: 4 },
        { id: 'sk12', name: 'Functional Safety', proficiency: 5 },
        { id: 'sk13', name: 'Cybersecurity', proficiency: 3 },
      ],
    },
    {
      id: 'sc3',
      name: 'Testing',
      description: 'HIL, SIL, VIL & automation frameworks',
      color: '#60a5fa',
      skills: [
        { id: 'sk14', name: 'HIL', proficiency: 5 },
        { id: 'sk15', name: 'SIL', proficiency: 4 },
        { id: 'sk16', name: 'VIL', proficiency: 4 },
        { id: 'sk17', name: 'CANoe', proficiency: 5 },
        { id: 'sk18', name: 'CANalyzer', proficiency: 5 },
        { id: 'sk19', name: 'Pytest', proficiency: 4 },
        { id: 'sk20', name: 'Regression', proficiency: 5 },
        { id: 'sk21', name: 'System Testing', proficiency: 5 },
      ],
    },
    {
      id: 'sc4',
      name: 'Coding',
      description: 'Python, CAPL, Embedded C scripting',
      color: '#a78bfa',
      skills: [
        { id: 'sk22', name: 'Python', proficiency: 4 },
        { id: 'sk23', name: 'Embedded C', proficiency: 4 },
        { id: 'sk24', name: 'CAPL', proficiency: 5 },
      ],
    },
    {
      id: 'sc5',
      name: 'Tools',
      description: 'ALM, CI/CD, version control toolchain',
      color: '#f97316',
      skills: [
        { id: 'sk25', name: 'Polarion', proficiency: 5 },
        { id: 'sk26', name: 'IBM DOORS', proficiency: 4 },
        { id: 'sk27', name: 'Jira', proficiency: 5 },
        { id: 'sk28', name: 'Gerrit', proficiency: 4 },
        { id: 'sk29', name: 'Git', proficiency: 5 },
        { id: 'sk30', name: 'vTestStudio', proficiency: 5 },
        { id: 'sk31', name: 'ETAS INCA', proficiency: 4 },
      ],
    },
  ],
  education: [
    {
      id: 'e1',
      degree: 'B.E. Computer Science Engineering',
      institution: 'Anna University',
      period: '2012 – 2016',
      location: 'Tamil Nadu, India',
      grade: 'CGPA 7.6',
    },
  ],
  certifications: [
    { id: 'ce1', name: 'ISO 26262:2018 Functional Safety', issuer: 'Professional Certification', year: '2021' },
    { id: 'ce2', name: 'Agile Project Management', issuer: 'Professional Certification', year: '2022' },
    { id: 'ce3', name: 'ISO 9001:2015 QMS', issuer: 'Professional Certification', year: '2022' },
    { id: 'ce4', name: 'Volvo Track License T1 & T2', issuer: 'Volvo Cars', year: '2024' },
  ],
  languages: [
    { id: 'lang1', name: 'English', completed: true },
    { id: 'lang2', name: 'Malayalam', completed: true },
    { id: 'lang3', name: 'Tamil', completed: true },
    { id: 'lang4', name: 'Kannada', completed: true },
    { id: 'lang5', name: 'Hindi', completed: true },
    { id: 'lang6', name: 'Telugu', completed: true },
  ],
  journey: [
    { id: 'j1', place: 'Pollachi',   country: 'India',  region: 'Asia',   lat: 10.659,  lng: 77.007,  startDate: '1994-01-01', endDate: '',           description: 'Hometown — where it all began.', images: [], fromPlace: '', fromCountry: '' },
    { id: 'j2', place: 'Chennai',    country: 'India',  region: 'Asia',   lat: 13.0827, lng: 80.2707, startDate: '2016-09-01', endDate: '2018-11-01', description: 'First professional chapter at TCS — Telematics & Infotainment ECU testing.', images: [], fromPlace: 'Pollachi',  fromCountry: 'India',  fromLat: 10.659,  fromLng: 77.007 },
    { id: 'j3', place: 'Bangalore',  country: 'India',  region: 'Asia',   lat: 12.9716, lng: 77.5946, startDate: '2018-11-01', endDate: '2021-11-01', description: 'Three years of AUTOSAR and ADAS at HCL for Ford safety-critical programs.', images: [], fromPlace: 'Chennai',   fromCountry: 'India',  fromLat: 13.0827, fromLng: 80.2707 },
    { id: 'j4', place: 'Mysore',     country: 'India',  region: 'Asia',   lat: 12.2958, lng: 76.6394, startDate: '2021-11-01', endDate: '2022-12-01', description: 'Led PODS platform testing at L&T Technology Services. 99% test coverage.', images: [], fromPlace: 'Bangalore', fromCountry: 'India',  fromLat: 12.9716, fromLng: 77.5946 },
    { id: 'j5', place: 'Gothenburg', country: 'Sweden', region: 'Europe', lat: 57.7089, lng: 11.9746, startDate: '2023-02-01', endDate: '',           description: 'Current home and base. Project Lead at Volvo Cars for EV exterior systems.', images: [], fromPlace: 'Mysore',    fromCountry: 'India',  fromLat: 12.2958, fromLng: 76.6394 },
    { id: 'j6', place: 'Paris',      country: 'France', region: 'Europe', lat: 48.8566, lng: 2.3522,  startDate: '2023-08-12', endDate: '2023-08-18', description: 'Eiffel Tower & Louvre. First Wonder ticked off.', images: [], fromPlace: 'Gothenburg',fromCountry: 'Sweden', fromLat: 57.7089, fromLng: 11.9746 },
    { id: 'j7', place: 'Pisa',       country: 'Italy',  region: 'Europe', lat: 43.7228, lng: 10.4017, startDate: '2024-04-05', endDate: '2024-04-09', description: 'Leaning Tower up close. Tuscan food, Tuscan light.', images: [], fromPlace: 'Gothenburg',fromCountry: 'Sweden', fromLat: 57.7089, fromLng: 11.9746 },
    { id: 'j8', place: 'Agra',       country: 'India',  region: 'Asia',   lat: 27.1751, lng: 78.0421, startDate: '2019-12-21', endDate: '2019-12-25', description: 'Taj Mahal at sunrise. Worth every degree of cold.', images: [], fromPlace: 'Bangalore', fromCountry: 'India',  fromLat: 12.9716, fromLng: 77.5946 },
  ],
  achievements: [
    {
      id: 'a1',
      name: '7 Wonders of the World',
      description: 'Visit all seven modern wonders',
      color: '#c9a84c',
      items: [
        { id: 'w1', text: 'Eiffel Tower — Paris, France', completed: true },
        { id: 'w2', text: 'Leaning Tower of Pisa — Pisa, Italy', completed: true },
        { id: 'w3', text: 'Taj Mahal — Agra, India', completed: true },
        { id: 'w4', text: 'Christ the Redeemer — Rio de Janeiro, Brazil', completed: false },
        { id: 'w5', text: 'Machu Picchu — Cusco, Peru', completed: false },
        { id: 'w6', text: 'Chichen Itza — Yucatán, Mexico', completed: false },
        { id: 'w7', text: "Petra — Ma'an, Jordan", completed: false },
      ],
    },
    {
      id: 'a2',
      name: 'Marathon Journey',
      description: '5K to Full Marathon progression',
      color: '#00ff87',
      items: [
        { id: 'm1', text: '5K Run', completed: false },
        { id: 'm2', text: '10K Run', completed: false },
        { id: 'm3', text: 'Half Marathon (21K)', completed: false },
        { id: 'm4', text: 'Full Marathon (42K)', completed: false },
      ],
    },
    {
      id: 'a3',
      name: 'Fitness Goals',
      description: 'Personal fitness milestones',
      color: '#60a5fa',
      items: [
        { id: 'f1', text: 'Do 50 consecutive push-ups', completed: false },
        { id: 'f2', text: 'Reach 66 kg target weight', completed: false },
      ],
    },
  ],
  globeSettings: {
    globeTexture: 'night',
    pinColor: '#00d4aa',
    pinSelectedColor: '#00ff87',
    atmosphereColor: '#00ff87',
    strokeColor: '#00ff87',
    arcColor: '#00ff87',
  },
}
